### ISSUE TITLE
Rendering is layered on top of itself

### ISSUE THREAD

**Issue by xrl** [brendandburns/gcp-live-k8s-visualizer#14]
Not working with my `1.5` series k8s cluster. Installed/running using the instructions from the README. Using Chrome 56.

Empty page flash:

![image](https://cloud.githubusercontent.com/assets/693059/23183073/9a8aa548-f82f-11e6-9adb-8867cbace4b2.png)

When it does render (briefly):

![image](https://cloud.githubusercontent.com/assets/693059/23183101/bde9253c-f82f-11e6-901b-6607d0e8e100.png)

**Comment by mitchhh22** [comment]
@xrl did you figure the issue out? 
I'm experiencing the same problem

**Comment by xrl** [comment]
No, I didn't figure it out. I just abandoned the work. Good luck!
